### PR TITLE
Fixing vulnerability with old version of uglify

### PR DESCRIPTION
**Pull request by CrossEye**

### CODE REVIEW

**Comment by davidchambers** [comment]
Will you publish a new release?

**Comment by Bradcomp** [comment]
:bowtie:

**Comment by CrossEye** [comment]
I think we'll have to, much as I don't really like to do anything with this.

I've done little with R-F.  Can anyone tell me if we've got the release process documented?

**Comment by davidchambers** [comment]
> Can anyone tell me if we've got the release process documented?

`npm run release-patch` should do the trick.

**Comment by CrossEye** [comment]
Yes, I can build and tag, but I guess I was never added to the list of npm authors.  Could someone who has access either add me or do a `publish`? 

@ramda/core @ramda/ramda-fantasy

**Comment by davidchambers** [comment]
I don't think a new release is necessary actually. As I understand it the UglifyJS vulnerability affects the `uglifyjs` program itself, not its output. Users of ramda-fantasy are unaffected.

**Comment by CrossEye** [comment]
Well, the npm package includes everything, `src`, `test`, etc.  Anyone could build from there.

So it seems safer to publish the updated version.

**Pull request merged**
