### PR TITLE
Ramda version bump

### PR DESCRIPTION
**Pull request by kujon**

### CODE REVIEW

**Comment by buzzdecafe** [comment]
thanks

**Comment by kujon** [comment]
np :) any chance of publishing soon?

**Comment by buzzdecafe** [comment]
hmmm i don't even recall what's new. is there something you need particularly?

**Comment by kujon** [comment]
version mismatch in ramda and ramda-fantasy makes module bundlers bundle 2 versions of ramda together, thus increasing the size of js file.

**Comment by buzzdecafe** [comment]
i can see that. i'll try to publish soon

**Comment by tusharmath** [comment]
Have you considered https://github.com/semantic-release/semantic-release, you could automate the release process completely.

**Comment by kujon** [comment]
@tusharmath using it ATM, it's awesome. The problem is when I bump Ramda version in my project and ramda-fantasy still references the older older version, I end up with 2 Ramdas in my bundle.

**Comment by tusharmath** [comment]
@kujon I think you should do a `npm ddp` before creating a bundle — https://docs.npmjs.com/cli/dedupe

**Comment by kujon** [comment]
@tusharmath would it affect the outcome if RF is `>=0.15.0 <=0.21.x` and my project is `0.22.x`?

**Comment by buzzdecafe** [comment]
maybe we should just change package.json to `>=0.15.0`

**Comment by tusharmath** [comment]
@kujon unfortunately in that case you will have two copies in the bundle.
@buzzdecafe greenkeeper is a good option together with https://github.com/semantic-release/semantic-release.

**Comment by buzzdecafe** [comment]
interesting stuff @tusharmath. thanks, i'll look into it

**Comment by kujon** [comment]
> maybe we should just change package.json to >=0.15.0
Didn't want to do it myself, but if we can assume RF will work with future iterations of ramda, then it's grand 👌

**Comment by buzzdecafe** [comment]
> if we can assume RF will work with future iterations of ramda

i think the big api swings are over. one big forthcoming issue is the reduction of placeholder support, but i don't think that would affect RF. So I'd be content to leave the interval half open [0.15.0, &infin;)

**Comment by buzzdecafe** [comment]
just published 0.6.1 which has no upper limit on R version

**Pull request merged**
