### PR TITLE
Adding chainReject for chaining operations off of failure cases. 

### PR DESCRIPTION
**Pull request by jethrolarson**
e.g. If you make a ajax request and you want to process error data differently than success data.

This is Task::orElse in folktale's data.task

### CODE REVIEW

**Comment by TheLudd** [comment]
Just thinking about the name here. A similar method could be added to `Either`.  Would it be a good idea to give them the same name? Same goes for mapping over the rejected or left value. Is there any standard terminology for this?

**Comment by jethrolarson** [comment]
There was some discussion on gitter. Switching all of Future terms to be
Left/Right is a thought. I'm not sure it makes it more learnable but it
would help the APIs line up. I expect most people learning Future will come
from Promises not Either

**Comment by jethrolarson** [comment]
Also chaining over left isn't part of monad or chain specification so there
might not be an established word. We should probably impl bichain and
bitmap for both of these though

**Comment by buzzdecafe** [comment]
i followed the conversation on gitter, and apart from the name i think this is a nice addition. We can either pull as is and revise the name later (my choice), or search for the ideal name and only merge when we've found it.

**Comment by jethrolarson** [comment]
Lib is still alpha, so merge is cheap

**Pull request merged**
