### PR TITLE
Tree-shake ramda by cherry-picking requires

### PR DESCRIPTION
**Pull request by jimf**
Slim down browserify-based environments by cherry-picking the needed
requirements from Ramda rather than pulling in the whole thing.

Style should be consistent with Ramda-proper's source.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
makes sense. :cow2:

**Comment by TheLudd** [comment]
How does this hold up using browserify? If I use browserify with ramda-fantasy and ramda when it is packaged this way, will it be the same size as before? Can I browserify ramda into a standalone bundle and ramda-fantasy into its own and still have the output no bigger than before?

**Comment by jimf** [comment]
@TheLudd I believe your questions are dependent on both the version of browserify you're using, as well as the version of npm. However, my understanding is that by doing it this way, the resulting build will never be larger, and in most cases, it will be smaller. I'd encourage you to test it though, particularly if those use cases describe your general build process.

**Comment by flintinatux** [comment]
👍  this. Importing all of `ramda` in front-end makes for huge builds.

**Comment by buzzdecafe** [comment]
sorry for the *long* delay. are you interested in repairing conflicts? i promise a prompt merge this time

**Comment by buzzdecafe** [comment]
#119 seems to have done this -- gonna close this one and merge that one

**Pull request closed without merging**
