### PR TITLE
add jshint

### PR DESCRIPTION
**Pull request by buzzdecafe**

### CODE REVIEW

**Comment by TheLudd** [comment]
Very nice.
Related to this, I noticed that the project does not have the same indentation everywhere (I am to blame for some of this). What is our policy here, do we go with 2/4?

**Comment by buzzdecafe** [comment]
i'm for 2 spaces

**Comment by TheLudd** [comment]
Should we fix that here or in another commit?

**Comment by buzzdecafe** [comment]
separate commit. may wanna include jscs for enforcement

**Pull request merged**
