### PR TITLE
automate release process

### PR DESCRIPTION
**Pull request by davidchambers**
Alternative to #41

```console
$ npm run release-{major,minor,patch}
```

### CODE REVIEW

**Comment by buzzdecafe** [comment]
i prefer this one. one less dependency

**Comment by davidchambers** [comment]
Works for me. :)

**Comment by TheLudd** [comment]
This could also be done as
```
"release-major": "xyz --repo git@github.com:ramda/ramda-fantasy.git --increment"
```
and then by running 
```
npm run release -- minor
```

**Comment by CrossEye** [comment]
Having recently been working on a Windows-only machine, I also prefer it!

**Comment by davidchambers** [comment]
That's good to know, @TheLudd. I like the slightly shorter version as it leverages muscle memory: I've run `make-release-{major,minor,patch}` hundreds of times at this point. :)

**Comment by TheLudd** [comment]
@CrossEye @davidchambers For both of you I actually don't get which version you are referring to =)

**Pull request merged**
