### PR TITLE
Fixes lint complaints

### PR DESCRIPTION
**Pull request by scott-christopher**

### CODE REVIEW

**Comment by TheLudd** [comment]
Are we not running travis? Is it possible to set up? These check should be done on every PR automatically.

**Comment by scott-christopher** [comment]
I just went to enable it before creating this PR, but it needs one of the project owners to enable it.

**Comment by buzzdecafe** [comment]
> it needs one of the project owners to enable it.

@TheLudd @scott-christopher done.

**Comment by scott-christopher** [comment]
Thanks @buzzdecafe. I've enabled Travis CI for this project and raised #69 to add the .travis.yml

**Pull request merged**
