### PR TITLE
Add Semigroup implementation for Maybe

### PR DESCRIPTION
**Pull request by i-am-tom**
The concatenation method has been added for the two instances of the Maybe type. Accompanying tests (just QuickChecks for the semigroup laws) have also been added.

I've tried to keep the implementations consistent with the code around them, so let me know if there's anything to change and I'll update!

### CODE REVIEW

**Comment by buzzdecafe** [comment]
Sorry for the delay. Just need to update the README table for Maybe x Semigroup; otherwise this looks fine to me -- any objections, anyone?

**Comment by i-am-tom** [comment]
Hah, fell at the last hurdle - sorted now! Apparently introduced a merge conflict, though, so sorry about that :(

**Comment by buzzdecafe** [comment]
can you please resolve the conflict and amend the commit?

**Comment by i-am-tom** [comment]
All sorted! :)

**Comment by buzzdecafe** [comment]
Thanks for your patience! This LGTM -- Gonna leave open until tomorrow to allow others to comment should they wish to -- otherwise I will merge then.

**Comment by buzzdecafe** [comment]
🐪

**Pull request merged**
