### PR TITLE
Updated to the newest version of Ramda

### PR DESCRIPTION
**Pull request by kujon**

### CODE REVIEW

**Comment by CrossEye** [comment]
Thank you.

**Comment by kujon** [comment]
np 😄

**Comment by kujon** [comment]
Any chance of publishing it quite soon?

**Comment by CrossEye** [comment]
Sorry, I've been disengaged from Ramda for a few weeks.  Just trying to catch up.

I actually know nothing about the publish process in RF.  Let's invoke a few others to see what they know.  @buzzdecafe, @TheLudd, @asaf-romano, @scott-christopher, @davidchambers, anyone have objections?

**Comment by buzzdecafe** [comment]
been soooooper busy lately. i will try and publish tonight. please ping me if i don't get to it timely

**Comment by kujon** [comment]
@buzzdecafe ping

**Comment by buzzdecafe** [comment]
dammit! thanks for the ping. sorry i am such a delinquent

**Comment by buzzdecafe** [comment]
https://www.npmjs.com/package/ramda-fantasy

thanks for the reminder

**Pull request merged**
