### PR TITLE
Add reject to Future

### PR DESCRIPTION
**Pull request by TheLudd**
Complement function to `of`. Creates a future that will be rejected with
the input value.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
:cow2:

are there laws we should be concerned about satisfying for `reject`?

**Comment by TheLudd** [comment]
I don't think so since it is completely outside the fantasy-land specification.

**Comment by CrossEye** [comment]
>> are there laws we should be concerned about satisfying for reject?

> I don't think so since it is completely outside the fantasy-land specification.

That might be a _non sequitur_.  We would have to decide on such laws and not leave it to the FanatasyLand team, but that doesn't mean that no such laws should exist.

**Comment by buzzdecafe** [comment]
will merge now, swing back later

**Pull request merged**
