### PR TITLE
Create a join method

### PR DESCRIPTION
**Pull request by idcmardelplata**
I think it would be good for the types to have a join method. Here is a simple implementation.

Obviously used like this:

```js
Maybe.prototype.join = getJoinForTypes(Maybe);
IO.prototype.join = getJoinForTypes(IO)
etc...
```

### CODE REVIEW

**Comment by davidchambers** [comment]
Are you imagining something like `join :: Chain m => m (m a) -> m a`, @idcmardelplata?

**Comment by idcmardelplata** [comment]
As it is, I do not understand why the types do not have method join.

**Comment by davidchambers** [comment]
[`join`][1] can be derived from `chain`. In my view we're better off defining `join` once and for all than having dozens of authors add `join` methods to their algebraic data types.


[1]: https://github.com/sanctuary-js/sanctuary-type-classes/blob/v2.0.1/index.js#L1250-L1268

**Comment by idcmardelplata** [comment]
As such, I think the same as you

**Pull request closed without merging**
