### PR TITLE
Add equality test for Future

### PR DESCRIPTION
**Pull request by TheLudd**

### CODE REVIEW

**Comment by TheLudd** [comment]
Draft of how future equality could work in the test environment.

**Comment by buzzdecafe** [comment]
interesting, and certainly better than what is (barely) there now

**Comment by TheLudd** [comment]
As I understand it, this should be enough to run all the tests in `test/types.js`

**Comment by buzzdecafe** [comment]
does it pass `npm test` now?

**Comment by TheLudd** [comment]
It passes `npm test`
I also added types tests. They pass..

**Comment by buzzdecafe** [comment]
:cow:

**Comment by TheLudd** [comment]
Coolers. Do we also add tests for `map`, `chain` et al? Like

```
var result = R.map(R.add(1), Future.of(1));
assert.equal(true, Future.of(2).equals(result)
```

**Comment by buzzdecafe** [comment]
yeah, i think we should have some way of distinguishing unit tests from "legal compliance" tests.

**Pull request merged**
